INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2019, 1, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 5, 2022, 1, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2023, 1, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (48000, 5, 2024, 2, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 4, 2021, 2, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (72000, 5, 2023, 3, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (70000, 5, 2023, 3, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2020, 3, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (43000, 4, 2020, 4, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2018, 4, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (94000, 9, 2018, 4, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 4, 2021, 4, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2021, 4, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2023, 5, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2020, 6, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2019, 6, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (80000, 9, 2021, 6, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2020, 6, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2022, 6, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (100000, 5, 2022, 7, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2022, 8, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 9, 2020, 8, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 7, 2019, 9, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2019, 10, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2024, 10, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2019, 10, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2024, 10, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 5, 2018, 11, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2024, 12, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2023, 12, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 5, 2019, 12, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2019, 12, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 5, 2020, 13, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2024, 13, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2020, 13, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 5, 2021, 13, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (92000, 5, 2019, 13, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2019, 14, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (48000, 5, 2023, 14, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2018, 14, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2019, 14, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 9, 2021, 14, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (21000, 4, 2022, 15, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (28000, 4, 2020, 15, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (35000, 5, 2019, 15, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2023, 15, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (89000, 5, 2023, 15, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (35000, 4, 2021, 16, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2018, 16, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2024, 17, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2019, 18, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2019, 18, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (61000, 5, 2024, 18, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2019, 18, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 5, 2018, 18, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2021, 19, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (35000, 4, 2021, 19, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2020, 20, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2021, 20, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (93000, 5, 2018, 21, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (55000, 5, 2020, 21, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (78000, 7, 2022, 21, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 9, 2022, 21, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (59000, 5, 2024, 22, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (69000, 5, 2024, 22, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2019, 22, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (29000, 4, 2023, 22, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (28000, 4, 2020, 22, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (86000, 7, 2024, 23, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2024, 24, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2021, 24, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2019, 25, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2019, 26, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (42000, 4, 2019, 26, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2020, 27, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 9, 2022, 27, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 5, 2023, 27, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (67000, 7, 2019, 27, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 7, 2022, 28, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (39000, 5, 2023, 28, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2023, 28, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (81000, 9, 2022, 29, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (99000, 7, 2022, 30, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2019, 30, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 4, 2024, 30, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2024, 30, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (61000, 5, 2018, 30, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (83000, 5, 2022, 31, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2023, 31, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 7, 2022, 31, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (41000, 4, 2024, 31, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 5, 2022, 32, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 5, 2021, 32, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 5, 2022, 33, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 5, 2020, 33, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (91000, 7, 2020, 33, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2019, 33, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 5, 2021, 34, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (87000, 5, 2022, 34, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (23000, 4, 2021, 34, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2024, 34, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (92000, 5, 2023, 34, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (58000, 5, 2021, 35, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 9, 2023, 36, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2024, 36, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 9, 2023, 37, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (108000, 5, 2022, 37, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2019, 37, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (25000, 4, 2024, 37, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 5, 2023, 37, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (25000, 4, 2024, 38, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2019, 38, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (78000, 9, 2019, 38, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (25000, 4, 2024, 39, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (63000, 11, 2021, 39, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 4, 2022, 39, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (43000, 4, 2024, 39, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 5, 2021, 39, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (96000, 5, 2019, 40, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (38000, 5, 2021, 40, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (89000, 9, 2021, 40, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (71000, 5, 2021, 40, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (29000, 4, 2023, 40, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (28000, 4, 2021, 41, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2020, 41, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (67000, 9, 2023, 41, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2023, 41, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2020, 42, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 7, 2022, 42, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 4, 2021, 42, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2023, 42, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (81000, 9, 2024, 43, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (67000, 5, 2018, 43, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2023, 43, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (87000, 7, 2021, 44, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (83000, 5, 2022, 44, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2019, 45, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (25000, 4, 2019, 45, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2022, 46, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 5, 2019, 46, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (48000, 5, 2024, 47, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (39000, 5, 2021, 47, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (38000, 5, 2018, 47, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2021, 48, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2019, 48, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 5, 2024, 48, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (118000, 5, 2023, 49, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 7, 2020, 49, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (38000, 4, 2024, 49, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2019, 49, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2023, 50, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (35000, 4, 2024, 50, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 5, 2024, 50, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 9, 2020, 50, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2023, 51, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (38000, 5, 2022, 51, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2019, 51, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2019, 52, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2020, 52, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 7, 2020, 52, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (119000, 5, 2018, 52, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (60000, 5, 2021, 53, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2022, 53, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 5, 2024, 53, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2019, 53, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 4, 2019, 53, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2019, 54, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 9, 2020, 54, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2018, 54, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 5, 2020, 54, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (38000, 5, 2019, 54, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2024, 55, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (48000, 5, 2024, 55, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2021, 55, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (21000, 4, 2022, 56, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (71000, 5, 2019, 56, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2021, 57, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2020, 57, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2018, 57, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2021, 58, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 5, 2021, 58, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2018, 58, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (92000, 5, 2020, 58, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 5, 2020, 59, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (86000, 5, 2018, 59, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (42000, 5, 2024, 59, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (100000, 5, 2022, 59, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 5, 2024, 59, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 5, 2024, 60, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 5, 2021, 60, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (92000, 5, 2018, 60, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2020, 61, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (74000, 7, 2023, 62, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2024, 63, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2022, 63, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (29000, 4, 2020, 63, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 4, 2019, 63, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (80000, 5, 2024, 63, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (43000, 4, 2019, 64, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 7, 2023, 65, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2024, 65, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2024, 65, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 4, 2019, 65, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2020, 66, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 11, 2018, 67, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (32000, 5, 2019, 67, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 5, 2022, 67, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 5, 2019, 68, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2018, 68, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (62000, 11, 2021, 68, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2021, 68, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2022, 69, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (72000, 9, 2023, 69, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2024, 69, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2018, 69, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (29000, 4, 2020, 69, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (81000, 9, 2021, 70, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2020, 70, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (99000, 7, 2023, 71, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 11, 2019, 71, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (89000, 5, 2023, 71, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (25000, 4, 2023, 71, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2018, 72, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (41000, 4, 2019, 72, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (81000, 11, 2024, 72, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2021, 72, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2018, 72, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 11, 2022, 73, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (23000, 4, 2018, 73, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2022, 73, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2022, 73, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (87000, 5, 2019, 74, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2023, 74, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 11, 2022, 74, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (70000, 5, 2024, 74, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (68000, 7, 2020, 75, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 5, 2020, 75, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2019, 75, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (62000, 5, 2018, 75, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2020, 76, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 7, 2022, 76, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (83000, 9, 2019, 77, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2023, 77, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2020, 77, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (62000, 5, 2019, 78, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 5, 2022, 78, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (63000, 11, 2020, 79, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (62000, 5, 2020, 79, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 9, 2018, 79, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (58000, 5, 2021, 80, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2020, 80, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (23000, 4, 2018, 80, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 4, 2024, 81, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2024, 81, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2023, 81, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 4, 2021, 82, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (92000, 9, 2022, 82, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2020, 82, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (41000, 5, 2020, 82, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (93000, 5, 2022, 83, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (43000, 5, 2024, 84, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 4, 2020, 85, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2020, 85, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2022, 86, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (74000, 5, 2018, 87, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (87000, 9, 2018, 87, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (67000, 7, 2019, 87, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2019, 87, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (43000, 5, 2018, 88, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2019, 89, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2019, 89, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (60000, 5, 2022, 89, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2021, 90, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2024, 90, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 5, 2020, 90, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 5, 2020, 91, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 4, 2019, 91, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2024, 91, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 7, 2023, 91, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2023, 91, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2024, 92, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 4, 2023, 92, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 5, 2023, 92, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 5, 2023, 92, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 5, 2018, 92, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (28000, 4, 2019, 93, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 7, 2020, 93, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 5, 2019, 93, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (35000, 5, 2021, 94, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (82000, 5, 2020, 95, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 5, 2023, 95, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (67000, 5, 2020, 95, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (82000, 11, 2024, 95, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2024, 95, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (90000, 5, 2024, 96, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2021, 96, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (60000, 11, 2020, 96, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2023, 97, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2021, 97, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 5, 2024, 97, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 5, 2022, 98, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 9, 2019, 99, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (69000, 9, 2018, 99, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (99000, 7, 2024, 99, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2020, 99, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (55000, 5, 2020, 99, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 5, 2018, 100, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 4, 2019, 100, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 7, 2024, 101, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 5, 2022, 101, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2021, 101, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2021, 101, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 11, 2024, 101, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (28000, 4, 2020, 102, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (63000, 11, 2019, 102, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (93000, 5, 2019, 103, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 5, 2022, 103, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (88000, 7, 2018, 103, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 4, 2021, 103, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (43000, 5, 2021, 104, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 4, 2021, 104, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2019, 104, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2018, 104, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 5, 2019, 104, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2024, 105, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (71000, 11, 2023, 105, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2020, 106, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 5, 2020, 106, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2024, 106, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (86000, 5, 2024, 107, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 5, 2022, 107, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2019, 107, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2019, 107, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2019, 108, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 5, 2023, 108, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (38000, 5, 2019, 108, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (93000, 5, 2019, 108, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (44000, 5, 2022, 109, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 7, 2020, 109, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (74000, 5, 2024, 109, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 5, 2024, 109, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2019, 109, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 5, 2021, 110, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2023, 110, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 5, 2024, 110, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2023, 110, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (68000, 7, 2024, 111, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2021, 112, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2019, 113, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 7, 2020, 113, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (118000, 5, 2023, 113, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2018, 113, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 4, 2023, 113, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2020, 114, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2024, 115, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (88000, 5, 2023, 115, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (28000, 4, 2024, 115, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (121000, 5, 2023, 115, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2024, 116, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 11, 2021, 116, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2022, 116, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 7, 2023, 116, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 5, 2022, 116, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 5, 2021, 117, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (70000, 5, 2019, 117, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (90000, 9, 2021, 117, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (120000, 5, 2023, 117, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (39000, 4, 2021, 117, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2019, 118, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 11, 2024, 118, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (21000, 4, 2018, 118, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 11, 2019, 119, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (71000, 5, 2021, 119, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 9, 2023, 120, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 5, 2024, 120, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (115000, 5, 2018, 121, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (63000, 5, 2022, 121, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 5, 2019, 121, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (21000, 4, 2018, 122, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 5, 2022, 122, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 5, 2022, 122, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (29000, 4, 2021, 122, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (24000, 4, 2021, 123, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2024, 123, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (124000, 5, 2021, 123, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2019, 124, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (39000, 5, 2018, 125, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (32000, 5, 2020, 125, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2023, 125, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (87000, 9, 2023, 125, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 5, 2023, 126, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (59000, 5, 2018, 126, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 5, 2018, 126, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (68000, 11, 2022, 126, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (86000, 7, 2024, 126, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (88000, 5, 2023, 127, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 5, 2020, 127, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2022, 127, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2020, 128, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (44000, 5, 2021, 128, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (42000, 4, 2021, 128, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2019, 129, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (92000, 5, 2018, 129, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (23000, 4, 2021, 129, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (80000, 9, 2024, 129, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (88000, 7, 2020, 129, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2023, 130, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (100000, 5, 2018, 130, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2023, 130, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 5, 2020, 130, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2020, 131, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 4, 2024, 131, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2020, 132, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (43000, 5, 2023, 132, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 9, 2020, 132, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (25000, 4, 2019, 132, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (70000, 5, 2023, 132, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 7, 2019, 133, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2020, 133, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2023, 133, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 4, 2019, 134, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2021, 134, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2022, 134, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (81000, 5, 2022, 134, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2022, 135, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2021, 136, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (120000, 5, 2024, 136, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2019, 136, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2021, 137, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (82000, 5, 2021, 137, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (40000, 5, 2022, 137, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 5, 2023, 137, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (74000, 5, 2018, 138, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2021, 139, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (55000, 5, 2021, 140, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2018, 140, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2020, 140, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 7, 2018, 140, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2021, 140, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (23000, 4, 2023, 141, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (48000, 5, 2021, 142, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (78000, 11, 2024, 142, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2022, 142, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2024, 142, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (29000, 4, 2023, 142, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 5, 2021, 143, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (125000, 5, 2022, 143, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2018, 144, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (67000, 5, 2023, 144, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2019, 144, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (71000, 9, 2019, 144, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2023, 145, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 7, 2022, 145, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2022, 145, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (125000, 5, 2020, 146, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (94000, 7, 2019, 147, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (74000, 5, 2020, 147, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (71000, 5, 2023, 148, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (88000, 9, 2024, 149, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (55000, 5, 2020, 149, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (39000, 5, 2022, 149, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (116000, 5, 2018, 150, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 4, 2018, 150, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (74000, 5, 2020, 150, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (78000, 7, 2022, 150, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (72000, 5, 2023, 151, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (81000, 5, 2020, 152, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (78000, 7, 2020, 152, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (63000, 5, 2018, 153, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2019, 153, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2020, 153, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (90000, 9, 2022, 153, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 11, 2024, 154, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (89000, 5, 2024, 154, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2024, 154, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 5, 2024, 154, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (127000, 5, 2019, 154, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2018, 155, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (68000, 7, 2022, 155, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 7, 2020, 155, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (88000, 9, 2021, 155, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2018, 156, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 4, 2021, 156, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (38000, 5, 2020, 156, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 9, 2019, 156, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 4, 2024, 156, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 5, 2019, 157, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2019, 158, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (25000, 4, 2019, 158, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2020, 159, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (62000, 5, 2024, 159, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 5, 2022, 159, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (44000, 5, 2021, 159, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (71000, 5, 2022, 159, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 7, 2024, 160, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2021, 160, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2021, 161, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2018, 162, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 5, 2021, 162, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (72000, 9, 2018, 162, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2023, 162, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (72000, 5, 2021, 162, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 11, 2023, 163, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2020, 163, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (55000, 5, 2024, 163, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 4, 2022, 163, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2023, 164, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (72000, 7, 2018, 164, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (78000, 5, 2018, 164, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (28000, 4, 2021, 165, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (96000, 7, 2021, 165, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (41000, 4, 2021, 165, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2018, 165, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2020, 165, '가솔린', '쏘나타', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (32000, 5, 2019, 166, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2020, 166, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (115000, 5, 2020, 167, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 5, 2023, 167, '가솔린', 'K3', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 5, 2022, 167, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (35000, 4, 2024, 167, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2022, 168, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (97000, 5, 2022, 168, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2022, 168, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2021, 168, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 4, 2021, 168, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (88000, 9, 2021, 169, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (68000, 7, 2024, 170, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (67000, 5, 2024, 170, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (55000, 5, 2018, 170, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 11, 2018, 170, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2020, 170, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (68000, 11, 2023, 171, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (111000, 5, 2020, 171, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2022, 171, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (87000, 9, 2020, 172, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 5, 2021, 172, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2021, 172, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (83000, 9, 2019, 172, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (42000, 5, 2023, 173, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 5, 2019, 173, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (93000, 7, 2019, 173, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 4, 2024, 173, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 4, 2019, 174, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (50000, 5, 2021, 174, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (84000, 9, 2024, 174, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 4, 2024, 174, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (61000, 5, 2023, 174, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (23000, 4, 2023, 175, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2019, 176, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2022, 176, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (114000, 5, 2024, 177, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (52000, 5, 2023, 177, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (71000, 9, 2021, 177, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 5, 2018, 178, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 9, 2018, 178, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 4, 2021, 178, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2019, 178, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2024, 179, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2018, 180, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (31000, 4, 2018, 180, '가솔린', '캐스퍼', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (27000, 4, 2022, 180, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 9, 2022, 180, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (95000, 5, 2019, 180, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (89000, 9, 2023, 181, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (54000, 5, 2023, 181, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (61000, 5, 2019, 182, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (25000, 4, 2021, 182, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (106000, 5, 2019, 182, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (68000, 7, 2023, 183, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 5, 2024, 183, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 5, 2020, 183, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (78000, 9, 2020, 183, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (28000, 4, 2024, 183, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (60000, 5, 2022, 184, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2018, 184, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (67000, 5, 2021, 184, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 5, 2022, 185, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 9, 2022, 185, '디젤', '스타리아', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (66000, 5, 2024, 186, '전기', '아이오닉5', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (46000, 5, 2024, 186, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (39000, 5, 2018, 187, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (44000, 5, 2019, 187, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (73000, 5, 2023, 187, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (68000, 7, 2023, 187, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 5, 2020, 188, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 11, 2018, 189, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (74000, 7, 2020, 190, '디젤', '싼타페', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (41000, 5, 2022, 190, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (64000, 5, 2021, 191, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (90000, 5, 2019, 191, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (44000, 5, 2023, 191, '전기', '볼트 EV', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 7, 2024, 191, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (70000, 5, 2023, 192, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2023, 192, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (55000, 5, 2019, 192, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (53000, 5, 2019, 193, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 4, 2019, 193, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (26000, 4, 2021, 194, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (59000, 5, 2022, 194, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (81000, 7, 2022, 194, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (61000, 5, 2018, 194, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (114000, 5, 2023, 195, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (33000, 5, 2021, 195, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 9, 2018, 195, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2021, 196, '가솔린', '모닝', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (81000, 9, 2021, 196, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (49000, 5, 2022, 196, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (77000, 5, 2023, 196, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (113000, 5, 2020, 197, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (85000, 7, 2022, 197, '디젤', '팰리세이드', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (48000, 5, 2020, 198, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (47000, 5, 2023, 199, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2019, 199, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (88000, 5, 2019, 199, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (56000, 5, 2022, 200, '가솔린', 'K5', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (58000, 5, 2020, 200, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (60000, 5, 2022, 201, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (90000, 5, 2021, 201, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (83000, 11, 2021, 201, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2019, 201, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (55000, 5, 2019, 202, '가솔린', '말리부', '중형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (70000, 11, 2019, 202, '디젤', '그랜드 스타렉스', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (79000, 5, 2024, 202, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 5, 2021, 202, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (22000, 4, 2018, 202, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (29000, 4, 2019, 203, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (34000, 4, 2021, 203, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (82000, 5, 2024, 203, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (20000, 4, 2020, 204, '가솔린', '스파크', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (51000, 5, 2020, 204, '가솔린', '티볼리', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (57000, 5, 2020, 204, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (93000, 5, 2021, 204, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (75000, 5, 2019, 204, '하이브리드', '그랜저', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (94000, 5, 2020, 205, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (58000, 5, 2019, 205, '디젤', '스포티지', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (83000, 5, 2020, 205, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (36000, 4, 2019, 205, '가솔린', '벨로스터', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (45000, 5, 2018, 206, '가솔린', '셀토스', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (29000, 4, 2024, 206, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (37000, 5, 2021, 206, '가솔린', '아반떼', '소형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (86000, 5, 2021, 206, '가솔린', 'K8', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (76000, 9, 2024, 206, '디젤', '카니발', '승합');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (63000, 5, 2024, 207, '가솔린', '투싼', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (122000, 5, 2020, 207, '가솔린', '제네시스 G80', '대형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (65000, 5, 2020, 207, '전기', 'EV6', 'SUV');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (30000, 4, 2024, 207, '가솔린', '레이', '경형');
INSERT INTO webdb.trip_car (daily_price, seats, year, company_id, fuel, name, type) VALUES (60000, 5, 2022, 207, '전기', '아이오닉5', 'SUV');
